# Generated by Django 5.0.2 on 2024-02-15 08:05

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Currency",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "charcode",
                    models.CharField(max_length=3, verbose_name="Код символа"),
                ),
                ("date", models.DateField(auto_now_add=True, verbose_name="Дата")),
                (
                    "rate",
                    models.DecimalField(
                        decimal_places=2, max_digits=5, verbose_name="Ставка к рублю"
                    ),
                ),
            ],
            options={
                "verbose_name": "Денежная единица",
                "ordering": ("date",),
            },
        ),
    ]
