# Generated by Django 5.0.2 on 2024-02-15 16:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("currency", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="currency",
            name="rate",
            field=models.FloatField(verbose_name="Ставка к рублю"),
        ),
    ]
