# Generated by Django 5.0.2 on 2024-02-15 16:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("currency", "0002_alter_currency_rate"),
    ]

    operations = [
        migrations.AlterField(
            model_name="currency",
            name="charcode",
            field=models.CharField(max_length=3, verbose_name="Код валюты"),
        ),
    ]
