# Generated by Django 5.0.2 on 2024-02-15 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("currency", "0003_alter_currency_charcode"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="currency",
            options={"verbose_name": "Денежная единица"},
        ),
        migrations.AlterField(
            model_name="currency",
            name="date",
            field=models.DateField(verbose_name="Дата"),
        ),
    ]
